server:
  port: 9000

spring:
  application:
    name: deploy-project

  # 데이터베이스 설정 (MySQL)
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/grapevine?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      # (create, create-drop, create-only, drop, truncate, update, validate, none)
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect

    # JPA/Hibernate 로그 설정
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  # 파일 업로드 설정 (Multipart)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # AWS S3 설정
#  cloud:
#    aws:
#      region:
#        static: ap-northeast-2
#      s3:
#        bucket: {버킷 이름 넣기}